### PR TITLE
Use aspnetcore 8 IExceptionHandler in project templates (#5801)

### LINKED ISSUE #5801: Use aspnetcore `IExceptionHandler` in project templates

### PR DESCRIPTION
**Pull request by ysmoradi**
This closes #5801

### CODE REVIEW

File: src/Templates/AdminPanel/Bit.AdminPanel/src/Shared/Dtos/Identity/SendEmailConfirmLinkRequestDto.cs [hunk 1]
```diff
@@ -5,7 +5,7 @@ namespace AdminPanel.Shared.Dtos.Identity;
 public class SendConfirmationEmailRequestDto
 {
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/AdminPanel/Bit.AdminPanel/src/Shared/Dtos/Identity/SendEmailConfirmLinkRequestDto.cs:8]: please roll this change back

File: src/Templates/AdminPanel/Bit.AdminPanel/src/Shared/Dtos/Identity/SignInRequestDto.cs [hunk 2]
```diff
@@ -6,7 +6,7 @@ public class SignInRequestDto
 {
     /// <example>me@gmail.com</example>
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/AdminPanel/Bit.AdminPanel/src/Shared/Dtos/Identity/SignInRequestDto.cs:9]: please roll this change back

File: src/Templates/AdminPanel/Bit.AdminPanel/src/Shared/Dtos/Identity/SignUpRequestDto.cs [hunk 3]
```diff
@@ -7,7 +7,7 @@ public class SignUpRequestDto
     /// The user's email
     /// </summary>
     /// <example>me@gmail.com</example>
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/AdminPanel/Bit.AdminPanel/src/Shared/Dtos/Identity/SignUpRequestDto.cs:10]: please roll this change back

File: src/Templates/AdminPanel/Bit.AdminPanel/src/Shared/Dtos/Identity/UserDto.cs [hunk 4]
```diff
@@ -8,12 +8,12 @@ public class UserDto
...
     // By default, username gets filled from email during signup in Api/Models/Mapper.cs class.
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
     [Display(Name = nameof(AppStrings.Email))]
     public string? UserName { get; set; }
 
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/AdminPanel/Bit.AdminPanel/src/Shared/Dtos/Identity/UserDto.cs:16]: please roll this change back

File: src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/EmailConfirmedRequestDto.cs [hunk 5]
```diff
@@ -4,7 +4,7 @@
 public class EmailConfirmedRequestDto
 {
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/EmailConfirmedRequestDto.cs:7]: please roll this change back

File: src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/ResetPasswordRequestDto.cs [hunk 6]
```diff
@@ -4,7 +4,7 @@
 public class ResetPasswordRequestDto
 {
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/ResetPasswordRequestDto.cs:7]: please roll this change back

File: src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/SendEmailConfirmLinkRequestDto.cs [hunk 7]
```diff
@@ -4,7 +4,7 @@
 public class SendConfirmationEmailRequestDto
 {
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError)),
-        EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+        EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/SendEmailConfirmLinkRequestDto.cs:7]: please roll this change back

File: src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/SendEmailForgotPasswordLinkRequestDto.cs [hunk 8]
```diff
@@ -4,7 +4,7 @@
 public class SendResetPasswordEmailRequestDto
 {
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/SendEmailForgotPasswordLinkRequestDto.cs:7]: please roll this change back

File: src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/SignInRequestDto.cs [hunk 9]
```diff
@@ -5,7 +5,7 @@ public class SignInRequestDto
 {
     /// <example>me@gmail.com</example>
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/SignInRequestDto.cs:8]: please roll this change back

File: src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/SignUpRequestDto.cs [hunk 10]
```diff
@@ -7,7 +7,7 @@ public class SignUpRequestDto
     /// The user's email
     /// </summary>
     /// <example>me@gmail.com</example>
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/SignUpRequestDto.cs:10]: please roll this change back

File: src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/UserDto.cs [hunk 11]
```diff
@@ -7,12 +7,12 @@ public class UserDto
 
     // By default, username gets filled from email during signup in Api/Models/Mapper.cs class.
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError)),
-        EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+        EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/UserDto.cs:10]: please roll this change back

File: src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/UserDto.cs [hunk 12]
```diff
@@ -7,12 +7,12 @@ public class UserDto
...
     [Display(Name = nameof(AppStrings.Email))]
     public string? UserName { get; set; }
 
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/UserDto.cs:15]: please roll this change back

File: src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/EmailConfirmedRequestDto.cs [hunk 13]
```diff
@@ -4,7 +4,7 @@
 public class EmailConfirmedRequestDto
 {
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/EmailConfirmedRequestDto.cs:7]: please roll this change back

File: src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/ResetPasswordRequestDto.cs [hunk 14]
```diff
@@ -4,7 +4,7 @@
 public class ResetPasswordRequestDto
 {
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/ResetPasswordRequestDto.cs:7]: please roll this change back

File: src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/ResetPasswordRequestDto.cs [hunk 15]
```diff
@@ -18,7 +18,7 @@ public class ResetPasswordRequestDto
 
     [NotMapped]
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [Compare(nameof(Password), ErrorMessage = nameof(AppStrings.CompareAttribute_ValidationError))]
+    [Compare(nameof(Password), ErrorMessage = nameof(AppStrings.CompareAttribute_MustMatch))]
```
Comment (msynk) [inline src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/ResetPasswordRequestDto.cs:21]: please roll this change back

File: src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/SendEmailConfirmLinkRequestDto.cs [hunk 16]
```diff
@@ -4,7 +4,7 @@
 public class SendConfirmationEmailRequestDto
 {
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError)),
-        EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+        EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/SendEmailConfirmLinkRequestDto.cs:7]: please roll this change back

File: src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/SendEmailForgotPasswordLinkRequestDto.cs [hunk 17]
```diff
@@ -4,7 +4,7 @@
 public class SendResetPasswordEmailRequestDto
 {
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/SendEmailForgotPasswordLinkRequestDto.cs:7]: please roll this change back

File: src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/SignInRequestDto.cs [hunk 18]
```diff
@@ -5,7 +5,7 @@ public class SignInRequestDto
 {
     /// <example>me@gmail.com</example>
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/SignInRequestDto.cs:8]: please roll this change back

File: src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/SignUpRequestDto.cs [hunk 19]
```diff
@@ -7,7 +7,7 @@ public class SignUpRequestDto
     /// The user's email
     /// </summary>
     /// <example>me@gmail.com</example>
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/SignUpRequestDto.cs:10]: please roll this change back

File: src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/UserDto.cs [hunk 20]
```diff
@@ -7,12 +7,12 @@ public class UserDto
 
     // By default, username gets filled from email during signup in Api/Models/Mapper.cs class.
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError)),
-        EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+        EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/UserDto.cs:10]: please roll this change back

File: src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/UserDto.cs [hunk 21]
```diff
@@ -7,12 +7,12 @@ public class UserDto
...
     [Display(Name = nameof(AppStrings.Email))]
     public string? UserName { get; set; }
 
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_ValidationError))]
+    [EmailAddress(ErrorMessage = nameof(AppStrings.EmailAddressAttribute_Invalid))]
```
Comment (msynk) [inline src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/UserDto.cs:15]: please roll this change back

File: src/Templates/AdminPanel/Bit.AdminPanel/src/Shared/Dtos/Identity/ResetPasswordRequestDto.cs [hunk 22]
```diff
@@ -19,7 +19,7 @@ public class ResetPasswordRequestDto
 
     [NotMapped]
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [Compare(nameof(Password), ErrorMessage = nameof(AppStrings.CompareAttribute_ValidationError))]
+    [Compare(nameof(Password), ErrorMessage = nameof(AppStrings.CompareAttribute_MustMatch))]
```
Comment (msynk) [inline src/Templates/AdminPanel/Bit.AdminPanel/src/Shared/Dtos/Identity/ResetPasswordRequestDto.cs:22]: please roll this change back

File: src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/ResetPasswordRequestDto.cs [hunk 23]
```diff
@@ -18,7 +18,7 @@ public class ResetPasswordRequestDto
 
     [NotMapped]
     [Required(ErrorMessage = nameof(AppStrings.RequiredAttribute_ValidationError))]
-    [Compare(nameof(Password), ErrorMessage = nameof(AppStrings.CompareAttribute_ValidationError))]
+    [Compare(nameof(Password), ErrorMessage = nameof(AppStrings.CompareAttribute_MustMatch))]
```
Comment (msynk) [inline src/Templates/BlazorDual/Bit.BlazorDual/src/BlazorDual.Shared/Dtos/Identity/ResetPasswordRequestDto.cs:21]: please roll this change back

**Review by msynk — CHANGES_REQUESTED** [review]

**Review by msynk — APPROVED** [review]
