### PR TITLE
Fix localization issue with pre rendering in `AdminPanel` project (#2963)

### LINKED ISSUE #2963: `AdminPanel` localization issue with pre rendering

### PR DESCRIPTION
**Pull request by msangtarash**
This closes #2963

### CODE REVIEW

File: src/Templates/AdminPanel/Bit.AdminPanel/Api/Controllers/CategoryController.cs [hunk 1]
```diff
@@ -1,5 +1,6 @@
 ﻿using AdminPanel.Api.Models.Categories;
 using AdminPanel.Shared.Dtos.Categories;
+using Microsoft.Extensions.Localization;
```
Comment (ysmoradi) [inline src/Templates/AdminPanel/Bit.AdminPanel/Api/Controllers/CategoryController.cs:3]: Remove this

**Review by ysmoradi — CHANGES_REQUESTED** [review]

**Review by ysmoradi — APPROVED** [review]

**Review by msynk — APPROVED** [review]
